[tool.poetry]
name = "KilluaRobot"
version = "0.4.7"
description = "Script for generating Telegram Session in Telethon or Pyrogram"
authors = ["unknownkz <iamkenzo404@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10.2"
Telethon = "^1.24.0"
TgCrypto = "^1.2.3"
Pyrogram = "^0.3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.12"]
build-backend = "poetry.masonry.api"
